### ISSUE TITLE
Mouse buttons for hotkeys?

### ISSUE THREAD

**Issue by peanutlasko** [apocc/pw-mods#3]
Hi @apocc , do you know if its possible to bind hotkeys to mousebuttons ? Like Mouse3/Mouse4/Mouse 5? 

Even if not in the UI, is there a way to do this inside the configs somewhere?

**Comment by apocc** [comment]
The current implementation via Unity Mod Manager doesn't support mouse buttons. The next version will use [ModMenu](https://github.com/WittleWolfie/ModMenu) to handle bindings and the native UI has mouse button support, at least for secondary buttons.

**Comment by apocc** [comment]
version 3 supports native UI bindings
